// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCophgbLVnUMv8AjmKxMAfGQOAXZ-k0quo',
    appId: '1:931973673687:web:846db7660573b8bafb7692',
    messagingSenderId: '931973673687',
    projectId: 'porfolio-b1ecc',
    authDomain: 'porfolio-b1ecc.firebaseapp.com',
    storageBucket: 'porfolio-b1ecc.firebasestorage.app',
    measurementId: 'G-TN3QTXZNH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6d-WUdXuPKMbXR7XoyWyL6D5gI5hMYlY',
    appId: '1:931973673687:android:2ea591f556bb18cafb7692',
    messagingSenderId: '931973673687',
    projectId: 'porfolio-b1ecc',
    storageBucket: 'porfolio-b1ecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAizH7G27ryCxb-P7pnTfJT3gwyze3HO4',
    appId: '1:931973673687:ios:cc8af58484497f7efb7692',
    messagingSenderId: '931973673687',
    projectId: 'porfolio-b1ecc',
    storageBucket: 'porfolio-b1ecc.firebasestorage.app',
    iosBundleId: 'com.example.porfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAizH7G27ryCxb-P7pnTfJT3gwyze3HO4',
    appId: '1:931973673687:ios:cc8af58484497f7efb7692',
    messagingSenderId: '931973673687',
    projectId: 'porfolio-b1ecc',
    storageBucket: 'porfolio-b1ecc.firebasestorage.app',
    iosBundleId: 'com.example.porfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCophgbLVnUMv8AjmKxMAfGQOAXZ-k0quo',
    appId: '1:931973673687:web:5ffb0d9a6099919afb7692',
    messagingSenderId: '931973673687',
    projectId: 'porfolio-b1ecc',
    authDomain: 'porfolio-b1ecc.firebaseapp.com',
    storageBucket: 'porfolio-b1ecc.firebasestorage.app',
    measurementId: 'G-V8Y99WJQN7',
  );

}